### PR TITLE
Update activator.js

### PR DESCRIPTION
**Pull request by matsprea**
Don't allow to activate a user with a token from another user

### CODE REVIEW

**Comment by deitch** [comment]
Thanks @matsprea we got this a few days ago. See https://github.com/deitch/activator/pull/41

**Comment by matsprea** [comment]
The problem is the same, but the #41 was for the password reset function, this one is for the user activation one.

**Comment by deitch** [comment]
Oh! Good catch, then. Thanks, fixing now.

**Comment by matsprea** [comment]
Thanks to you for your great package!

**Pull request merged**
