### PR TITLE
Possibility to send attachments in activation and reset mails from config

### PR DESCRIPTION
**Pull request by bartolkaruza**
Created this small extension for our need to pass cid attachments to sendmail for the activation and password reset emails. Might be useful for others. I didn't see an easy way to extend the unit tests for this functionality. All current tests are passing. Any ideas on how the unit tests for the attachments can be added?

### CODE REVIEW

**Comment by deitch** [comment]
That's pretty cool. So it just passes the arguments all the way through, allows it to accept an `attachments` property of the config, and sets an empty default? I like that.

Is the format of the attachment just the nodemailer standard attachments?

**Comment by bartolkaruza** [comment]
Yup, just Nodemailer standard as described here: https://github.com/andris9/Nodemailer#attachments

**Comment by deitch** [comment]
Yeah, I really like andris9's work in this.

So the only missing pieces here are:

1. README update
2. Unit tests

I am going to think through the unit tests and then merge it in.

**Comment by deitch** [comment]
Done in 1.1.0 with unit tests and all. Added your name to contributors. Thanks for the help.

**Pull request merged**
