### PR TITLE
Enable email property and id property to be deeper than model root

### PR DESCRIPTION
**Pull request by clifg**

### CODE REVIEW

**Comment by clifg** [comment]
I wanted to be able to reuse my existing user model, which doesn't have the email address as a root property (ie: "user = { id: "2", facebook: {...}, local: {email: "foo@bar.com"...} }"). While I was at it I decided to do the same for the idProperty, even though that seems less likely to be buried in the object. :)

Added tests and everything is passing:
> activator@1.2.2 test /Users/cgordon/Projects/activator
> mocha

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.

  activator
<...snip...>
        with email property override in model child object
          ✓ activate should succeed for known user 
          ✓ activate should fail on bad property 
          ✓ password reset should succeed for known email 
<...snip...>
        with id property override in model child object
          ✓ activate should succeed for known user 
          ✓ activate should fail on bad property 
          ✓ password reset should succeed for known email 
<...snip...>

  82 passing (1s)

**Comment by deitch** [comment]
This is quite nice. I like it. Can you update the README.md as well as to how to use this, and then it can be merged right in?

**Comment by clifg** [comment]
Sure, just updated the readme as well. Thanks for reviewing!

**Comment by deitch** [comment]
Thanks for the PR. So easy to work with when the new functionality includes the right tests.

**Pull request merged**
