### PR TITLE
Function for templates

### PR DESCRIPTION
**Pull request by miqmago**
https://github.com/deitch/activator/issues/49

### CODE REVIEW

**Comment by deitch** [comment]
Thanks! Will get to this soon. Very busy this week, off Mon-Tue and in Berlin speaking at LinuxCon/ContainerCon Wed-Thu.

**Comment by deitch** [comment]
@miqmago this is impressive. There are 4 commits. Can you comment when you feel you are done, and then I can review? There are some changes I would like to make (mostly stylistic) and the entire pull needs to be rebased since we pulled in the other changes you had in the `README.md`.

Most importantly, though, it does need tests.

Tell me when you are ready, can review.

**Comment by miqmago** [comment]
Hope you say impressive for the code not for the 4 commits :P.
I've finished and it's working (tested in real production app). Haven't had time to go deep in tests.

To rebase, what is required? Maybe I can delete the fork and post only the changes in code. That would be a pitty as I've described in `README.md` the whole features... Also I'm not very experienced rebasing (to be honest I've already tried to rebase but every time I try to rebase there are so many issues that I end by leaving it be).

**Comment by deitch** [comment]
> Hope you say impressive for the code not for the 4 commits :P.
Ha!

I will look at it later in the week

**Comment by deitch** [comment]
@miqmago take a look at the other PR I opened. I had to change the interface slightly, but mostly adopted your comments. It is integrated into 3.0.0.

Thanks again!

**Comment by miqmago** [comment]
You made it a lot easier and it's cool! Thanks a lot! :)

**Pull request closed without merging**
