### PR TITLE
secureConnection -> secure

### PR DESCRIPTION
**Pull request by menway**
nodemailer is now using option 'secure' to indicate secure connection, see: https://github.com/andris9/nodemailer-smtp-transport

### CODE REVIEW

**Comment by deitch** [comment]
Nice catch. As of which version of nodemailer is this? Is this for all versions 1.x and up, i.e. this is a bug with the current activator release?

**Comment by menway** [comment]
Just found that option was implemented in package smtp-connection, here is the commit (v.0.1.7) for the name change:
https://github.com/andris9/smtp-connection/commit/85639311910645cfce5519bfde7f2bf355881e55

**Comment by deitch** [comment]
Just realized you had commented; email notification was automatically marked as read. How strange.

**Comment by deitch** [comment]
OK, so:

* Activator depends on nodemailer 1.3.0, which depends upon:
** nodemailer-direct-transport 1.0.0, which depends upon smtp-connection 0.1.5
** nodemailer-smtp-transport 0.1.12, which depends upon smtp-connection smtp-connection 1.0.0

So using `secure` is clean from 0.1.7 onwards. Is there a concern that nodemailer 1.3.0 could be broken, because it depends deep down on smtp-connection 0.1.5?

**Comment by deitch** [comment]
Ah, here we go. If we make the minimum nodemailer 1.3.4, it depends upon:

* nodemailer-direct-transport 1.0.2, which depends upon smtp-connection 1.2.0
* nodemailer-smtp-transport 1.0.2, which depends upon smtp-connection 1.2.0

So the patch should *both* fix `secureConnection` to `secure` *and* update nodemailer dependency to >=1.3.4.

I will update, rerun tests, and publish shortly.

**Comment by deitch** [comment]
Pushed and published.

**Pull request closed without merging**
