### PR TITLE
configuration function to add custom headers to email

### PR DESCRIPTION
**Pull request by ghost**
The title should be clear, i needed to add this function for my project.

### CODE REVIEW

**Comment by deitch** [comment]
Hi @csprea . Thanks for this. I like the idea of custom headers, and especially appreciate proper tests and updating the README.

Please bump the version on `package.json` and `package-lock.json` and we can get it out.

**Comment by csprea** [comment]
Hi @deitch , hope bumping the minor was correct, and i fixed a comment in on of my test.

**Comment by deitch** [comment]
Absolutely correct. Fits with [semver](https://semver.org): we made a change that adds functionality but is backwards compatible, so minor version bump.

**Comment by deitch** [comment]
And published. Thank you!

**Comment by ghost** [comment]
no problem, you're welcome, thank you for the library.

**Comment by deitch** [comment]
Happy to see it well used! Do you mind sharing what service you use it for? If you don't want it to be in public, let me know and I can give you an email address.

**Comment by ghost** [comment]
It's a service to advertise small stores.

**Comment by deitch** [comment]
Interesting. Is there a Web site? I would like to see it.

**Comment by ghost** [comment]
You cannot see much without an account it's in italian and is on invite only, but i can send you the address on private anyway if you give me an email.

**Comment by deitch** [comment]
I’d be happy to see t. I’ll ask a colleague who is more conversant in Italian to help me. 

avi [at] atomicinc [dot] com

**Pull request merged**
